name: ci

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2

    - name: build and run tests
      run: |
        make
      env:
        CI: true
